<?php add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6633d18e8a094',
	'title' => 'BLOCK -> card carousel',
	'fields' => array(
		array(
			'key' => 'field_663501b0119b3',
			'label' => 'Cards',
			'name' => 'cards',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_663502584d0ca',
					'label' => 'Titel',
					'name' => 'titel',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_663501b0119b3',
				),
				array(
					'key' => 'field_663501edef79d',
					'label' => 'Tekst',
					'name' => 'tekst',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
					'parent_repeater' => 'field_663501b0119b3',
				),
				array(
					'key' => 'field_663501f55aad7',
					'label' => 'Afbeelding',
					'name' => 'afbeelding',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_663501b0119b3',
				),
				array(
					'key' => 'field_663501ff5aad8',
					'label' => 'Knop URL',
					'name' => 'knop_url',
					'aria-label' => '',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'post_status' => '',
					'taxonomy' => '',
					'allow_archives' => 1,
					'multiple' => 0,
					'allow_null' => 0,
					'parent_repeater' => 'field_663501b0119b3',
				),
			),
		),
		array(
			'key' => 'field_663526c2ec0b8',
			'label' => 'Aantal cards',
			'name' => 'aantal_cards',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 4,
			'min' => 1,
			'max' => 6,
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6635121bb8145',
			'label' => 'Titel kleur',
			'name' => 'titelkleur',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'zwart-color' => 'Zwart',
				'wit' => 'Wit',
				'grijs' => 'Grijs',
				'primary-color' => 'Primair kleur',
				'secondary-color' => 'Secundair kleur',
			),
			'default_value' => 'zwart',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'layout' => 'vertical',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_66350ee945e2f',
			'label' => 'Tekst kleur',
			'name' => 'tekstkleur',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'zwart' => 'Zwart',
				'wit' => 'Wit',
				'grijs' => 'Grijs',
				'primary-color' => 'Primair kleur',
				'secondary-color' => 'Secundair kleur',
			),
			'default_value' => 'zwart',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'layout' => 'vertical',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_66350f0345e30',
			'label' => 'Achtergrond kleur',
			'name' => 'achtergrond',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'geen' => 'Geen',
				'zwart' => 'Zwart',
				'wit' => 'Wit',
				'grijs' => 'Grijs',
				'primary-color' => 'Primair kleur',
				'secondary-color' => 'Secundair kleur',
			),
			'default_value' => 'zwart',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'layout' => 'vertical',
			'save_other_choice' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'flavus/card-carousel',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );

?>